расставляет Декоративные элементы на главной странице
htmlacademy-htmlcss/1123257-nerds-30 pull request #10
Opened 2021-02-23 22:37 UTC by Vkhv73

2021-02-24 08:38 UTC, PavelNyukalo requested changes

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +}
По сути лишние свойства, если их убрать ничего не меняется

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +  margin-left: -1px;
Можно не задавать такие правила, ничего страшного, если будет не соответствие на 1рх

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +  position: absolute;
Зачем здесь абсолютное позиционирование?

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +}
Там еще тень небольшая есть
![изображение](https://user-images.githubusercontent.com/52506235/108968007-07a58680-76a2-11eb-8f34-40c620b64e50.png)

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +  fill-opacity: 0.3;
Здесь можно просто у `svg` менять opacity
```css
.social-button:active svg {
  opacity: 0.3;
 }
```

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +  padding-right: 303px;
Чтобы не высчитывать все эти `padding-right`, `margin-bottom/top...` у дочерних можно задать все `.footer-bottom`
![изображение](https://user-images.githubusercontent.com/52506235/108969104-6c151580-76a3-11eb-8789-804924a0d78d.png)

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +  padding-right: 100px;
Опять же, чтобы не задавать каждый раз `padding`, можно всей секции модалки задать паддинги
![изображение](https://user-images.githubusercontent.com/52506235/108972671-602a5300-76a5-11eb-9795-c60f257189b6.png)

2021-02-24 08:38 UTC, PavelNyukalo commented on css/style.css
> +  left: 849px;
Легче же от правой границы задать

2021-02-24 20:59 UTC, Vkhv73 commented on index.html
> +      </div>
Сделал через border-radius: 50%. Не могу сообразить как центрировать картинку на выбранной и как идентифицировать выбранный слайд.

2021-02-24 21:41 UTC, Vkhv73 commented on index.html
> +    <section class="promo container">
Убрал .container. Для настройки пагинации обернул всё в див.

2021-02-24 21:54 UTC, Vkhv73 commented on css/style.css
> +}
.promo-pagination убрал.
Вроде бы и остальное поправил. Не разобрался только как применить картинку к выбранному слайду.

2021-02-24 22:09 UTC, Vkhv73 commented on css/style.css
> +}
Объединил стили.
Высоту заменил на min-height.

2021-02-28 12:50 UTC, Vkhv73 commented on css/style.css
>    font-size: 26px;
Сделал.

2021-02-28 12:51 UTC, Vkhv73 commented on css/style.css
> +}
Сделал.

2021-02-28 12:51 UTC, Vkhv73 commented on css/style.css
>  }
Убрал.

2021-02-28 12:52 UTC, Vkhv73 commented on css/style.css
> +}
Закомментировал.

2021-02-28 12:54 UTC, Vkhv73 commented on css/style.css
> +  margin-left: -1px;
Оставил пока что..

2021-02-28 13:02 UTC, Vkhv73 commented on css/style.css
> +  position: absolute;
Убрал.

2021-02-28 13:04 UTC, Vkhv73 commented on css/style.css
> +  fill-opacity: 0.3;
Поменял.

2021-02-28 16:47 UTC, Vkhv73 commented on css/style.css
> +  padding-right: 100px;
частично поправил.

2021-03-02 08:18 UTC, PavelNyukalo approved these changes

2021-03-02 08:18 UTC, merged