оформляет Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1123257-nerds-30 pull request #11
Opened 2021-03-03 07:07 UTC by Vkhv73

2021-03-03 11:20 UTC, PavelNyukalo requested changes

2021-03-03 11:20 UTC, PavelNyukalo commented on css/style.css
>  .pagination-item{
Вот [ссылка на пример пагинации](https://codesandbox.io/s/weathered-hooks-rzd1y?file=/style.css)

2021-03-03 11:20 UTC, PavelNyukalo commented on css/style.css
> +  width: 260px;
Тут не надо ширину, мы ее гриду задали и весь фильтр у нас 260рх
![image](https://user-images.githubusercontent.com/52506235/109798255-5a4fe700-7c3c-11eb-85a7-b259ebcdf90c.png)

2021-03-03 11:30 UTC, Vkhv73 commented on catalog.html
> +  <link rel="stylesheet" href="css/style-cat.css">
Сделал.

2021-03-03 11:30 UTC, Vkhv73 commented on css/style.css
> +  margin-bottom: 110px;
Сделал.

2021-03-03 12:13 UTC, Vkhv73 commented on css/style.css
> +  text-transform: uppercase;
Сделал.

2021-03-03 13:14 UTC, Vkhv73 commented on css/style.css
>    background-image: url(../img/checkbox-off.svg);
Сделал. Вроде бы. Как смог.

2021-03-04 01:37 UTC, Vkhv73 commented on css/style.css
>  }
Сделал.

2021-03-04 01:39 UTC, Vkhv73 commented on css/style.css
> +  width: 260px;
Сделал.

2021-03-04 02:19 UTC, Vkhv73 commented on css/style.css
>  .pagination-item{
Сделал, опираясь на пример.

2021-03-04 02:20 UTC, Vkhv73 commented on css/style.css
> +  width: 260px;
Убрал.

2021-03-04 18:02 UTC, PavelNyukalo approved these changes

2021-03-04 18:02 UTC, merged